server:
  port: 5053
db:
  name: salesorderdb
spring:
  h2:
    console:
      enabled: true
  #kafka:
   # bootstrap-servers: localhost:9092
    #consumer:
     # group-id: myGroup
  mail:
    host: localhost
    port: 25
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
     
#currency-exchangeservice:
 # ribbon:
  #  listOfServers: http://localhost:5555
ui:
  serverUrl: http://localhost:4200/ 
management:
  endpoints:
    web:
      exposure:
        include: '*'
